import type { Metadata } from "next";
import { Rubik, Geist, Geist_Mono } from "next/font/google";
import Provider from "./Provider";
import { headers } from 'next/headers';
import "./globals.css";
import { redirect } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const getRubik = Rubik({
  variable: "--font-rubik-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Food Ordering Application",
  description: "Generated by Yoedd.org",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>
}>) {
  const param: {lang: string} = await params;
  if(!param.lang.toLowerCase().startsWith("fr") && !param.lang.toLowerCase().startsWith("en") && !param.lang.toLowerCase().startsWith("ar"))
    redirect("/fr");
  return (
    <html lang={param.lang} suppressHydrationWarning>
      <body
        className={`${getRubik.variable} ${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
